services:
  strapi:
    volumes:
      - type: bind
        source: /data
        target: /opt/data
    build: ./guitarBE/
  nginx:
    build: ./nginx/
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email r.f.hylands@gmail.com -d api.practicethatguitar.co.uk --agree-tos