/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ArtistResponseDataObject } from './artistResponseDataObject';
import type { ArtistResponseMeta } from './artistResponseMeta';

export interface ArtistResponse {
  data?: ArtistResponseDataObject;
  meta?: ArtistResponseMeta;
}
