/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ArtistUserDataAttributesRole } from './artistUserDataAttributesRole';
import type { ArtistUserDataAttributesCreatedBy } from './artistUserDataAttributesCreatedBy';
import type { ArtistUserDataAttributesUpdatedBy } from './artistUserDataAttributesUpdatedBy';

export type ArtistUserDataAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: ArtistUserDataAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ArtistUserDataAttributesCreatedBy;
  updatedBy?: ArtistUserDataAttributesUpdatedBy;
};
