/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesPermissions } from './exerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesPermissions';
import type { ExerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesUsers } from './exerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesUsers';
import type { ExerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesCreatedBy } from './exerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesCreatedBy';
import type { ExerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesUpdatedBy } from './exerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesUpdatedBy';

export type ExerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: ExerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesPermissions;
  users?: ExerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesCreatedBy;
  updatedBy?: ExerciseResponseDataObjectLocalizedAttributesOwnerDataAttributesRoleDataAttributesUpdatedBy;
};
