/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesRelated } from './exerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesRelated';
import type { ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesFolder } from './exerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesFolder';
import type { ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy } from './exerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy';
import type { ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy } from './exerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy';

export type ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesRelated;
  folder?: ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy;
  updatedBy?: ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy;
};
