/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesRelated } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesRelated';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolder } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolder';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesCreatedBy } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesCreatedBy';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesUpdatedBy } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesUpdatedBy';

export type ExerciseResponseDataObjectLocalizedAttributesTabDataAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesRelated;
  folder?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesCreatedBy;
  updatedBy?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesUpdatedBy;
};
