/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributesRole } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributesRole';
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributesCreatedBy } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributesCreatedBy';
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributesUpdatedBy } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributesUpdatedBy';

export type ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributesCreatedBy;
  updatedBy?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwnerDataAttributesUpdatedBy;
};
