/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseUserDataAttributesRoleDataAttributesPermissions } from './exerciseUserDataAttributesRoleDataAttributesPermissions';
import type { ExerciseUserDataAttributesRoleDataAttributesUsers } from './exerciseUserDataAttributesRoleDataAttributesUsers';
import type { ExerciseUserDataAttributesRoleDataAttributesCreatedBy } from './exerciseUserDataAttributesRoleDataAttributesCreatedBy';
import type { ExerciseUserDataAttributesRoleDataAttributesUpdatedBy } from './exerciseUserDataAttributesRoleDataAttributesUpdatedBy';

export type ExerciseUserDataAttributesRoleDataAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: ExerciseUserDataAttributesRoleDataAttributesPermissions;
  users?: ExerciseUserDataAttributesRoleDataAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseUserDataAttributesRoleDataAttributesCreatedBy;
  updatedBy?: ExerciseUserDataAttributesRoleDataAttributesUpdatedBy;
};
