/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type ExercisePracticeExerciseDataAttributesSongStatusStatus = typeof ExercisePracticeExerciseDataAttributesSongStatusStatus[keyof typeof ExercisePracticeExerciseDataAttributesSongStatusStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExercisePracticeExerciseDataAttributesSongStatusStatus = {
  'TO-LEARN': 'TO-LEARN',
  LEARNING: 'LEARNING',
  PRACTISING: 'PRACTISING',
  FORGOT: 'FORGOT',
} as const;
