/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResponseDataObjectAttributesTabDataAttributesRelated } from './exerciseResponseDataObjectAttributesTabDataAttributesRelated';
import type { ExerciseResponseDataObjectAttributesTabDataAttributesFolder } from './exerciseResponseDataObjectAttributesTabDataAttributesFolder';
import type { ExerciseResponseDataObjectAttributesTabDataAttributesCreatedBy } from './exerciseResponseDataObjectAttributesTabDataAttributesCreatedBy';
import type { ExerciseResponseDataObjectAttributesTabDataAttributesUpdatedBy } from './exerciseResponseDataObjectAttributesTabDataAttributesUpdatedBy';

export type ExerciseResponseDataObjectAttributesTabDataAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: ExerciseResponseDataObjectAttributesTabDataAttributesRelated;
  folder?: ExerciseResponseDataObjectAttributesTabDataAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseResponseDataObjectAttributesTabDataAttributesCreatedBy;
  updatedBy?: ExerciseResponseDataObjectAttributesTabDataAttributesUpdatedBy;
};
