/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedByDataAttributes } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedByDataAttributes';

export type ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedByData = {
  id?: number;
  attributes?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedByDataAttributes;
};
