/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesRelated } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesRelated';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesFolder } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesFolder';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy';

export type ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesRelated;
  folder?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy;
  updatedBy?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy;
};
