/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExercisePracticeResponseDataObject } from './exercisePracticeResponseDataObject';
import type { ExercisePracticeResponseMeta } from './exercisePracticeResponseMeta';

export interface ExercisePracticeResponse {
  data?: ExercisePracticeResponseDataObject;
  meta?: ExercisePracticeResponseMeta;
}
