/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTabDataAttributes } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTabDataAttributes';

export type ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTabData = {
  id?: number;
  attributes?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTabDataAttributes;
};
