/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributes } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributes';

export type ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByData = {
  id?: number;
  attributes?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributes;
};
