/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedBy } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedBy';
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesUpdatedBy } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesUpdatedBy';

export type ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributes = {
  name?: string;
  description?: string;
  info?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedBy;
  updatedBy?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesUpdatedBy;
};
