/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesExercise } from './exerciseHistoryResponseDataObjectLocalizedAttributesExercise';
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesOwner } from './exerciseHistoryResponseDataObjectLocalizedAttributesOwner';
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesCreatedBy } from './exerciseHistoryResponseDataObjectLocalizedAttributesCreatedBy';
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesUpdatedBy } from './exerciseHistoryResponseDataObjectLocalizedAttributesUpdatedBy';

export type ExerciseHistoryResponseDataObjectLocalizedAttributes = {
  BPM?: number;
  speed?: string;
  comments?: string;
  exercise?: ExerciseHistoryResponseDataObjectLocalizedAttributesExercise;
  owner?: ExerciseHistoryResponseDataObjectLocalizedAttributesOwner;
  lengthMinutes?: number;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseHistoryResponseDataObjectLocalizedAttributesCreatedBy;
  updatedBy?: ExerciseHistoryResponseDataObjectLocalizedAttributesUpdatedBy;
};
