/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwner } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwner';
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTab } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTab';
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTags } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTags';
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesCreatedBy } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesCreatedBy';
import type { ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesUpdatedBy } from './exerciseHistoryResponseDataObjectAttributesExerciseDataAttributesUpdatedBy';

export type ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributes = {
  Name?: string;
  Description?: string;
  Owner?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesOwner;
  video?: string;
  metronome?: boolean;
  tab?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTab;
  guide?: string;
  tags?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesTags;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesCreatedBy;
  updatedBy?: ExerciseHistoryResponseDataObjectAttributesExerciseDataAttributesUpdatedBy;
};
