/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesRelated } from './exerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesRelated';
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesFolder } from './exerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesFolder';
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesCreatedBy } from './exerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesCreatedBy';
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesUpdatedBy } from './exerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesUpdatedBy';

export type ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesRelated;
  folder?: ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesCreatedBy;
  updatedBy?: ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesTabDataAttributesUpdatedBy;
};
