/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributesRole } from './exerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributesRole';
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributesCreatedBy } from './exerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributesCreatedBy';
import type { ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributesUpdatedBy } from './exerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributesUpdatedBy';

export type ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributesCreatedBy;
  updatedBy?: ExerciseHistoryResponseDataObjectLocalizedAttributesExerciseDataAttributesOwnerDataAttributesUpdatedBy;
};
