/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles } from './exerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles';
import type { ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy } from './exerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy';
import type { ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy } from './exerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy';

export type ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy;
  updatedBy?: ExerciseResponseDataObjectAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy;
};
