/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy';

export type ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesCreatedBy;
  updatedBy?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedBy;
};
