/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseUser } from './exerciseUser';
import type { ExerciseCreatedBy } from './exerciseCreatedBy';
import type { ExerciseUpdatedBy } from './exerciseUpdatedBy';

export interface Exercise {
  name: string;
  description: string;
  user?: ExerciseUser;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseCreatedBy;
  updatedBy?: ExerciseUpdatedBy;
}
