/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExercisePracticeExerciseDataAttributesUser } from './exercisePracticeExerciseDataAttributesUser';
import type { ExercisePracticeExerciseDataAttributesCreatedBy } from './exercisePracticeExerciseDataAttributesCreatedBy';
import type { ExercisePracticeExerciseDataAttributesUpdatedBy } from './exercisePracticeExerciseDataAttributesUpdatedBy';

export type ExercisePracticeExerciseDataAttributes = {
  name?: string;
  description?: string;
  user?: ExercisePracticeExerciseDataAttributesUser;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExercisePracticeExerciseDataAttributesCreatedBy;
  updatedBy?: ExercisePracticeExerciseDataAttributesUpdatedBy;
};
