/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRole } from './exerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRole';
import type { ExerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy } from './exerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy';
import type { ExerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy } from './exerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy';

export type ExerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributes = {
  action?: string;
  role?: ExerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: ExerciseUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy;
};
