/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResponseDataObjectLocalizedAttributesUpdatedByDataAttributes } from './exerciseResponseDataObjectLocalizedAttributesUpdatedByDataAttributes';

export type ExerciseResponseDataObjectLocalizedAttributesUpdatedByData = {
  id?: number;
  attributes?: ExerciseResponseDataObjectLocalizedAttributesUpdatedByDataAttributes;
};
