/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesParent } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesParent';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesChildren } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesChildren';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFiles } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFiles';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesCreatedBy } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesCreatedBy';
import type { ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesUpdatedBy } from './exerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesUpdatedBy';

export type ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributes = {
  name?: string;
  pathId?: number;
  parent?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesParent;
  children?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesChildren;
  files?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesFiles;
  path?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesCreatedBy;
  updatedBy?: ExerciseResponseDataObjectLocalizedAttributesTabDataAttributesFolderDataAttributesUpdatedBy;
};
