/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type GetAuthEmailConfirmationParams = {
/**
 * confirmation token received by email
 */
confirmation?: string;
};
