/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthForgotPassword200Ok = typeof PostAuthForgotPassword200Ok[keyof typeof PostAuthForgotPassword200Ok];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthForgotPassword200Ok = {
  true: 'true',
} as const;
