/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUser } from './usersPermissionsUser';
import type { PostUsers201AllOf } from './postUsers201AllOf';

export type PostUsers201 = UsersPermissionsUser & PostUsers201AllOf;
