/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type PostUsersPermissionsRoles200Ok = typeof PostUsersPermissionsRoles200Ok[keyof typeof PostUsersPermissionsRoles200Ok];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUsersPermissionsRoles200Ok = {
  true: 'true',
} as const;
