/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthSendEmailConfirmation200Sent = typeof PostAuthSendEmailConfirmation200Sent[keyof typeof PostAuthSendEmailConfirmation200Sent];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthSendEmailConfirmation200Sent = {
  true: 'true',
} as const;
