/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUser } from './usersPermissionsUser';
import type { PutUsersId200AllOf } from './putUsersId200AllOf';

export type PutUsersId200 = UsersPermissionsUser & PutUsersId200AllOf;
