/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type RoutineExerciseExerciseDataAttributesSongStatusStatus = typeof RoutineExerciseExerciseDataAttributesSongStatusStatus[keyof typeof RoutineExerciseExerciseDataAttributesSongStatusStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoutineExerciseExerciseDataAttributesSongStatusStatus = {
  'TO-LEARN': 'TO-LEARN',
  LEARNING: 'LEARNING',
  PRACTISING: 'PRACTISING',
  FORGOT: 'FORGOT',
} as const;
