/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleDataAttributes } from './routineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleDataAttributes';

export type RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleData = {
  id?: number;
  attributes?: RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleDataAttributes;
};
