/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineResponseDataObjectAttributesOwner } from './routineResponseDataObjectAttributesOwner';
import type { RoutineResponseDataObjectAttributesCreatedBy } from './routineResponseDataObjectAttributesCreatedBy';
import type { RoutineResponseDataObjectAttributesUpdatedBy } from './routineResponseDataObjectAttributesUpdatedBy';

export type RoutineResponseDataObjectAttributes = {
  Name?: string;
  owner?: RoutineResponseDataObjectAttributesOwner;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineResponseDataObjectAttributesCreatedBy;
  updatedBy?: RoutineResponseDataObjectAttributesUpdatedBy;
};
