/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleDataAttributes } from './routineUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleDataAttributes';

export type RoutineUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleData = {
  id?: number;
  attributes?: RoutineUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleDataAttributes;
};
