/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwner } from './routinePracticeResponseDataObjectAttributesRoutineDataAttributesOwner';
import type { RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesCreatedBy } from './routinePracticeResponseDataObjectAttributesRoutineDataAttributesCreatedBy';
import type { RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesUpdatedBy } from './routinePracticeResponseDataObjectAttributesRoutineDataAttributesUpdatedBy';

export type RoutinePracticeResponseDataObjectAttributesRoutineDataAttributes = {
  Name?: string;
  owner?: RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwner;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesCreatedBy;
  updatedBy?: RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesUpdatedBy;
};
