/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissions } from './routineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissions';
import type { RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUsers } from './routineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUsers';
import type { RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesCreatedBy } from './routineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesCreatedBy';
import type { RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUpdatedBy } from './routineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUpdatedBy';

export type RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissions;
  users?: RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesCreatedBy;
  updatedBy?: RoutineResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUpdatedBy;
};
