/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributesOwner } from './routinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributesOwner';
import type { RoutinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributesCreatedBy } from './routinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributesCreatedBy';
import type { RoutinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributesUpdatedBy } from './routinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributesUpdatedBy';

export type RoutinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributes = {
  Name?: string;
  owner?: RoutinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributesOwner;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributesCreatedBy;
  updatedBy?: RoutinePracticeResponseDataObjectLocalizedAttributesRoutineDataAttributesUpdatedBy;
};
