/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineExerciseRequestDataExercise } from './routineExerciseRequestDataExercise';
import type { RoutineExerciseRequestDataUser } from './routineExerciseRequestDataUser';
import type { RoutineExerciseRequestDataRoutine } from './routineExerciseRequestDataRoutine';

export type RoutineExerciseRequestData = {
  order?: number;
  exercise?: RoutineExerciseRequestDataExercise;
  user?: RoutineExerciseRequestDataUser;
  practiceTime?: number;
  routine?: RoutineExerciseRequestDataRoutine;
};
