/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineResponseDataObjectAttributesUpdatedByDataAttributes } from './routineResponseDataObjectAttributesUpdatedByDataAttributes';

export type RoutineResponseDataObjectAttributesUpdatedByData = {
  id?: number;
  attributes?: RoutineResponseDataObjectAttributesUpdatedByDataAttributes;
};
