/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesOwner } from './routineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesOwner';
import type { RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTab } from './routineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTab';
import type { RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTags } from './routineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTags';
import type { RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesCreatedBy } from './routineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesCreatedBy';
import type { RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesUpdatedBy } from './routineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesUpdatedBy';

export type RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributes = {
  Name?: string;
  Description?: string;
  Owner?: RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesOwner;
  video?: string;
  metronome?: boolean;
  tab?: RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTab;
  guide?: string;
  tags?: RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTags;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesCreatedBy;
  updatedBy?: RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesUpdatedBy;
};
