/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesRole } from './routinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesRole';
import type { RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesCreatedBy } from './routinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesCreatedBy';
import type { RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesUpdatedBy } from './routinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesUpdatedBy';

export type RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesCreatedBy;
  updatedBy?: RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesUpdatedBy;
};
