/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesPermissions } from './routineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesPermissions';
import type { RoutineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesUsers } from './routineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesUsers';
import type { RoutineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesCreatedBy } from './routineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesCreatedBy';
import type { RoutineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesUpdatedBy } from './routineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesUpdatedBy';

export type RoutineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: RoutineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesPermissions;
  users?: RoutineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesCreatedBy;
  updatedBy?: RoutineExerciseExerciseDataAttributesUserDataAttributesRoleDataAttributesUpdatedBy;
};
