/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTagsDataItemAttributesCreatedBy } from './routineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTagsDataItemAttributesCreatedBy';
import type { RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTagsDataItemAttributesUpdatedBy } from './routineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTagsDataItemAttributesUpdatedBy';

export type RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTagsDataItemAttributes = {
  name?: string;
  description?: string;
  info?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTagsDataItemAttributesCreatedBy;
  updatedBy?: RoutineExerciseResponseDataObjectLocalizedAttributesExerciseDataAttributesTagsDataItemAttributesUpdatedBy;
};
