/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutinePracticeResponseDataObjectAttributesCreatedByDataAttributes } from './routinePracticeResponseDataObjectAttributesCreatedByDataAttributes';

export type RoutinePracticeResponseDataObjectAttributesCreatedByData = {
  id?: number;
  attributes?: RoutinePracticeResponseDataObjectAttributesCreatedByDataAttributes;
};
