/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineExerciseExerciseDataAttributesUser } from './routineExerciseExerciseDataAttributesUser';
import type { RoutineExerciseExerciseDataAttributesSongStatus } from './routineExerciseExerciseDataAttributesSongStatus';
import type { RoutineExerciseExerciseDataAttributesCreatedBy } from './routineExerciseExerciseDataAttributesCreatedBy';
import type { RoutineExerciseExerciseDataAttributesUpdatedBy } from './routineExerciseExerciseDataAttributesUpdatedBy';

export type RoutineExerciseExerciseDataAttributes = {
  name?: string;
  description?: string;
  user?: RoutineExerciseExerciseDataAttributesUser;
  songStatus?: RoutineExerciseExerciseDataAttributesSongStatus;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineExerciseExerciseDataAttributesCreatedBy;
  updatedBy?: RoutineExerciseExerciseDataAttributesUpdatedBy;
};
