/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutinePracticeRoutineData } from './routinePracticeRoutineData';

export type RoutinePracticeRoutine = {
  data?: RoutinePracticeRoutineData;
};
