/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributesRole } from './routineResponseDataObjectLocalizedAttributesOwnerDataAttributesRole';
import type { RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributesCreatedBy } from './routineResponseDataObjectLocalizedAttributesOwnerDataAttributesCreatedBy';
import type { RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributesUpdatedBy } from './routineResponseDataObjectLocalizedAttributesOwnerDataAttributesUpdatedBy';

export type RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributesCreatedBy;
  updatedBy?: RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributesUpdatedBy;
};
