/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineExerciseExerciseDataAttributesUserDataAttributes } from './routineExerciseExerciseDataAttributesUserDataAttributes';

export type RoutineExerciseExerciseDataAttributesUserData = {
  id?: number;
  attributes?: RoutineExerciseExerciseDataAttributesUserDataAttributes;
};
