/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineResponseDataObjectLocalizedAttributesOwner } from './routineResponseDataObjectLocalizedAttributesOwner';
import type { RoutineResponseDataObjectLocalizedAttributesCreatedBy } from './routineResponseDataObjectLocalizedAttributesCreatedBy';
import type { RoutineResponseDataObjectLocalizedAttributesUpdatedBy } from './routineResponseDataObjectLocalizedAttributesUpdatedBy';

export type RoutineResponseDataObjectLocalizedAttributes = {
  Name?: string;
  owner?: RoutineResponseDataObjectLocalizedAttributesOwner;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineResponseDataObjectLocalizedAttributesCreatedBy;
  updatedBy?: RoutineResponseDataObjectLocalizedAttributesUpdatedBy;
};
