/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributesUpdatedByDataAttributes } from './routineResponseDataObjectLocalizedAttributesOwnerDataAttributesUpdatedByDataAttributes';

export type RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributesUpdatedByData = {
  id?: number;
  attributes?: RoutineResponseDataObjectLocalizedAttributesOwnerDataAttributesUpdatedByDataAttributes;
};
