/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineExerciseResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedBy } from './routineExerciseResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedBy';
import type { RoutineExerciseResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesUpdatedBy } from './routineExerciseResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesUpdatedBy';

export type RoutineExerciseResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributes = {
  name?: string;
  description?: string;
  info?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineExerciseResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesCreatedBy;
  updatedBy?: RoutineExerciseResponseDataObjectAttributesExerciseDataAttributesTagsDataItemAttributesUpdatedBy;
};
