/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesPermissions } from './routinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesPermissions';
import type { RoutinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesUsers } from './routinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesUsers';
import type { RoutinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesCreatedBy } from './routinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesCreatedBy';
import type { RoutinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesUpdatedBy } from './routinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesUpdatedBy';

export type RoutinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: RoutinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesPermissions;
  users?: RoutinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesCreatedBy;
  updatedBy?: RoutinePracticeRoutineDataAttributesUserDataAttributesRoleDataAttributesUpdatedBy;
};
