/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutineExerciseResponseDataObjectAttributesRoutine } from './routineExerciseResponseDataObjectAttributesRoutine';
import type { RoutineExerciseResponseDataObjectAttributesExercise } from './routineExerciseResponseDataObjectAttributesExercise';
import type { RoutineExerciseResponseDataObjectAttributesCreatedBy } from './routineExerciseResponseDataObjectAttributesCreatedBy';
import type { RoutineExerciseResponseDataObjectAttributesUpdatedBy } from './routineExerciseResponseDataObjectAttributesUpdatedBy';

export type RoutineExerciseResponseDataObjectAttributes = {
  routine?: RoutineExerciseResponseDataObjectAttributesRoutine;
  exercise?: RoutineExerciseResponseDataObjectAttributesExercise;
  order?: number;
  duration?: number;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: RoutineExerciseResponseDataObjectAttributesCreatedBy;
  updatedBy?: RoutineExerciseResponseDataObjectAttributesUpdatedBy;
};
