/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedByDataAttributes } from './routinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedByDataAttributes';

export type RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedByData = {
  id?: number;
  attributes?: RoutinePracticeResponseDataObjectAttributesRoutineDataAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedByDataAttributes;
};
