/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleDataAttributes } from './songResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleDataAttributes';

export type SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleData = {
  id?: number;
  attributes?: SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissionsDataItemAttributesRoleDataAttributes;
};
