/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongResponseDataObjectAttributesStatus } from './songResponseDataObjectAttributesStatus';
import type { SongResponseDataObjectAttributesOwner } from './songResponseDataObjectAttributesOwner';
import type { SongResponseDataObjectAttributesCreatedBy } from './songResponseDataObjectAttributesCreatedBy';
import type { SongResponseDataObjectAttributesUpdatedBy } from './songResponseDataObjectAttributesUpdatedBy';

export type SongResponseDataObjectAttributes = {
  title?: string;
  artist?: string;
  status?: SongResponseDataObjectAttributesStatus;
  owner?: SongResponseDataObjectAttributesOwner;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: SongResponseDataObjectAttributesCreatedBy;
  updatedBy?: SongResponseDataObjectAttributesUpdatedBy;
};
