/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRole } from './songUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRole';
import type { SongUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy } from './songUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy';
import type { SongUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy } from './songUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy';

export type SongUserDataAttributesRoleDataAttributesPermissionsDataItemAttributes = {
  action?: string;
  role?: SongUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: SongUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: SongUserDataAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy;
};
