/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongResponseDataObjectLocalizedAttributesStatus } from './songResponseDataObjectLocalizedAttributesStatus';
import type { SongResponseDataObjectLocalizedAttributesOwner } from './songResponseDataObjectLocalizedAttributesOwner';
import type { SongResponseDataObjectLocalizedAttributesCreatedBy } from './songResponseDataObjectLocalizedAttributesCreatedBy';
import type { SongResponseDataObjectLocalizedAttributesUpdatedBy } from './songResponseDataObjectLocalizedAttributesUpdatedBy';

export type SongResponseDataObjectLocalizedAttributes = {
  title?: string;
  artist?: string;
  status?: SongResponseDataObjectLocalizedAttributesStatus;
  owner?: SongResponseDataObjectLocalizedAttributesOwner;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: SongResponseDataObjectLocalizedAttributesCreatedBy;
  updatedBy?: SongResponseDataObjectLocalizedAttributesUpdatedBy;
};
