/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongUserDataAttributesRoleDataAttributesPermissions } from './songUserDataAttributesRoleDataAttributesPermissions';
import type { SongUserDataAttributesRoleDataAttributesUsers } from './songUserDataAttributesRoleDataAttributesUsers';
import type { SongUserDataAttributesRoleDataAttributesCreatedBy } from './songUserDataAttributesRoleDataAttributesCreatedBy';
import type { SongUserDataAttributesRoleDataAttributesUpdatedBy } from './songUserDataAttributesRoleDataAttributesUpdatedBy';

export type SongUserDataAttributesRoleDataAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: SongUserDataAttributesRoleDataAttributesPermissions;
  users?: SongUserDataAttributesRoleDataAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: SongUserDataAttributesRoleDataAttributesCreatedBy;
  updatedBy?: SongUserDataAttributesRoleDataAttributesUpdatedBy;
};
