/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongArtistDataAttributesCreatedByDataAttributes } from './songArtistDataAttributesCreatedByDataAttributes';

export type SongArtistDataAttributesCreatedByData = {
  id?: number;
  attributes?: SongArtistDataAttributesCreatedByDataAttributes;
};
