/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongResponseDataObjectAttributesOwnerDataAttributesRole } from './songResponseDataObjectAttributesOwnerDataAttributesRole';
import type { SongResponseDataObjectAttributesOwnerDataAttributesCreatedBy } from './songResponseDataObjectAttributesOwnerDataAttributesCreatedBy';
import type { SongResponseDataObjectAttributesOwnerDataAttributesUpdatedBy } from './songResponseDataObjectAttributesOwnerDataAttributesUpdatedBy';

export type SongResponseDataObjectAttributesOwnerDataAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: SongResponseDataObjectAttributesOwnerDataAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: SongResponseDataObjectAttributesOwnerDataAttributesCreatedBy;
  updatedBy?: SongResponseDataObjectAttributesOwnerDataAttributesUpdatedBy;
};
