/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongArtistDataAttributesUser } from './songArtistDataAttributesUser';
import type { SongArtistDataAttributesCreatedBy } from './songArtistDataAttributesCreatedBy';
import type { SongArtistDataAttributesUpdatedBy } from './songArtistDataAttributesUpdatedBy';

export type SongArtistDataAttributes = {
  name?: string;
  user?: SongArtistDataAttributesUser;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: SongArtistDataAttributesCreatedBy;
  updatedBy?: SongArtistDataAttributesUpdatedBy;
};
