/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type SongRequestDataStatus = typeof SongRequestDataStatus[keyof typeof SongRequestDataStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SongRequestDataStatus = {
  To_Learn: 'To Learn',
  Learning: 'Learning',
  Practising: 'Practising',
  'Learnt_(Not_Current)': 'Learnt (Not Current)',
} as const;
