/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongResponseDataObject } from './songResponseDataObject';
import type { SongResponseMeta } from './songResponseMeta';

export interface SongResponse {
  data?: SongResponseDataObject;
  meta?: SongResponseMeta;
}
