/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissions } from './songResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissions';
import type { SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUsers } from './songResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUsers';
import type { SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesCreatedBy } from './songResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesCreatedBy';
import type { SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUpdatedBy } from './songResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUpdatedBy';

export type SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesPermissions;
  users?: SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesCreatedBy;
  updatedBy?: SongResponseDataObjectAttributesOwnerDataAttributesRoleDataAttributesUpdatedBy;
};
