/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type TagListResponseMetaPagination = {
  page?: number;
  pageSize?: number;
  pageCount?: number;
  total?: number;
};
