/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TagListResponseDataItemAttributesCreatedByDataAttributesRoles } from './tagListResponseDataItemAttributesCreatedByDataAttributesRoles';
import type { TagListResponseDataItemAttributesCreatedByDataAttributesCreatedBy } from './tagListResponseDataItemAttributesCreatedByDataAttributesCreatedBy';
import type { TagListResponseDataItemAttributesCreatedByDataAttributesUpdatedBy } from './tagListResponseDataItemAttributesCreatedByDataAttributesUpdatedBy';

export type TagListResponseDataItemAttributesCreatedByDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: TagListResponseDataItemAttributesCreatedByDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: TagListResponseDataItemAttributesCreatedByDataAttributesCreatedBy;
  updatedBy?: TagListResponseDataItemAttributesCreatedByDataAttributesUpdatedBy;
};
