/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TagListResponseDataItemLocalizedAttributesCreatedBy } from './tagListResponseDataItemLocalizedAttributesCreatedBy';
import type { TagListResponseDataItemLocalizedAttributesUpdatedBy } from './tagListResponseDataItemLocalizedAttributesUpdatedBy';

export type TagListResponseDataItemLocalizedAttributes = {
  name?: string;
  description?: string;
  info?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: TagListResponseDataItemLocalizedAttributesCreatedBy;
  updatedBy?: TagListResponseDataItemLocalizedAttributesUpdatedBy;
};
