/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TagListResponseDataItem } from './tagListResponseDataItem';
import type { TagListResponseMeta } from './tagListResponseMeta';

export interface TagListResponse {
  data?: TagListResponseDataItem[];
  meta?: TagListResponseMeta;
}
