/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TagResponseDataObjectAttributesCreatedByDataAttributesRoles } from './tagResponseDataObjectAttributesCreatedByDataAttributesRoles';
import type { TagResponseDataObjectAttributesCreatedByDataAttributesCreatedBy } from './tagResponseDataObjectAttributesCreatedByDataAttributesCreatedBy';
import type { TagResponseDataObjectAttributesCreatedByDataAttributesUpdatedBy } from './tagResponseDataObjectAttributesCreatedByDataAttributesUpdatedBy';

export type TagResponseDataObjectAttributesCreatedByDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: TagResponseDataObjectAttributesCreatedByDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: TagResponseDataObjectAttributesCreatedByDataAttributesCreatedBy;
  updatedBy?: TagResponseDataObjectAttributesCreatedByDataAttributesUpdatedBy;
};
