/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TagResponseDataObjectAttributesCreatedBy } from './tagResponseDataObjectAttributesCreatedBy';
import type { TagResponseDataObjectAttributesUpdatedBy } from './tagResponseDataObjectAttributesUpdatedBy';

export type TagResponseDataObjectAttributes = {
  name?: string;
  description?: string;
  info?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: TagResponseDataObjectAttributesCreatedBy;
  updatedBy?: TagResponseDataObjectAttributesUpdatedBy;
};
