/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole } from './tagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole';
import type { TagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy } from './tagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy';
import type { TagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy } from './tagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy';

export type TagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributes = {
  action?: string;
  subject?: string;
  properties?: unknown;
  conditions?: unknown;
  role?: TagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: TagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: TagResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy;
};
