/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesUsers } from './testResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesUsers';
import type { TestResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissions } from './testResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissions';
import type { TestResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedBy } from './testResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedBy';
import type { TestResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedBy } from './testResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedBy';

export type TestResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributes = {
  name?: string;
  code?: string;
  description?: string;
  users?: TestResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesUsers;
  permissions?: TestResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesPermissions;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: TestResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesCreatedBy;
  updatedBy?: TestResponseDataObjectAttributesCreatedByDataAttributesRolesDataItemAttributesUpdatedBy;
};
