/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestListResponseDataItemLocalizedAttributesCreatedByDataAttributesRoles } from './testListResponseDataItemLocalizedAttributesCreatedByDataAttributesRoles';
import type { TestListResponseDataItemLocalizedAttributesCreatedByDataAttributesCreatedBy } from './testListResponseDataItemLocalizedAttributesCreatedByDataAttributesCreatedBy';
import type { TestListResponseDataItemLocalizedAttributesCreatedByDataAttributesUpdatedBy } from './testListResponseDataItemLocalizedAttributesCreatedByDataAttributesUpdatedBy';

export type TestListResponseDataItemLocalizedAttributesCreatedByDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: TestListResponseDataItemLocalizedAttributesCreatedByDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: TestListResponseDataItemLocalizedAttributesCreatedByDataAttributesCreatedBy;
  updatedBy?: TestListResponseDataItemLocalizedAttributesCreatedByDataAttributesUpdatedBy;
};
