/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestResponseDataObjectLocalizedAttributesCreatedByDataAttributesRoles } from './testResponseDataObjectLocalizedAttributesCreatedByDataAttributesRoles';
import type { TestResponseDataObjectLocalizedAttributesCreatedByDataAttributesCreatedBy } from './testResponseDataObjectLocalizedAttributesCreatedByDataAttributesCreatedBy';
import type { TestResponseDataObjectLocalizedAttributesCreatedByDataAttributesUpdatedBy } from './testResponseDataObjectLocalizedAttributesCreatedByDataAttributesUpdatedBy';

export type TestResponseDataObjectLocalizedAttributesCreatedByDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: TestResponseDataObjectLocalizedAttributesCreatedByDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: TestResponseDataObjectLocalizedAttributesCreatedByDataAttributesCreatedBy;
  updatedBy?: TestResponseDataObjectLocalizedAttributesCreatedByDataAttributesUpdatedBy;
};
