/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestListResponseDataItemAttributes } from './testListResponseDataItemAttributes';

export interface TestListResponseDataItem {
  id?: number;
  attributes?: TestListResponseDataItemAttributes;
}
