/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestListResponseDataItemLocalizedAttributesCreatedBy } from './testListResponseDataItemLocalizedAttributesCreatedBy';
import type { TestListResponseDataItemLocalizedAttributesUpdatedBy } from './testListResponseDataItemLocalizedAttributesUpdatedBy';

export type TestListResponseDataItemLocalizedAttributes = {
  name?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: TestListResponseDataItemLocalizedAttributesCreatedBy;
  updatedBy?: TestListResponseDataItemLocalizedAttributesUpdatedBy;
};
