/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestResponseDataObjectLocalizedAttributesCreatedBy } from './testResponseDataObjectLocalizedAttributesCreatedBy';
import type { TestResponseDataObjectLocalizedAttributesUpdatedBy } from './testResponseDataObjectLocalizedAttributesUpdatedBy';

export type TestResponseDataObjectLocalizedAttributes = {
  name?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: TestResponseDataObjectLocalizedAttributesCreatedBy;
  updatedBy?: TestResponseDataObjectLocalizedAttributesUpdatedBy;
};
