/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestListResponseDataItemLocalizedAttributesCreatedByDataAttributesCreatedByDataAttributes } from './testListResponseDataItemLocalizedAttributesCreatedByDataAttributesCreatedByDataAttributes';

export type TestListResponseDataItemLocalizedAttributesCreatedByDataAttributesCreatedByData = {
  id?: number;
  attributes?: TestListResponseDataItemLocalizedAttributesCreatedByDataAttributesCreatedByDataAttributes;
};
