/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestListResponseDataItemAttributesCreatedByDataAttributesCreatedByData } from './testListResponseDataItemAttributesCreatedByDataAttributesCreatedByData';

export type TestListResponseDataItemAttributesCreatedByDataAttributesCreatedBy = {
  data?: TestListResponseDataItemAttributesCreatedByDataAttributesCreatedByData;
};
