/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestListResponseDataItemAttributesCreatedByDataAttributesRoles } from './testListResponseDataItemAttributesCreatedByDataAttributesRoles';
import type { TestListResponseDataItemAttributesCreatedByDataAttributesCreatedBy } from './testListResponseDataItemAttributesCreatedByDataAttributesCreatedBy';
import type { TestListResponseDataItemAttributesCreatedByDataAttributesUpdatedBy } from './testListResponseDataItemAttributesCreatedByDataAttributesUpdatedBy';

export type TestListResponseDataItemAttributesCreatedByDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: TestListResponseDataItemAttributesCreatedByDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: TestListResponseDataItemAttributesCreatedByDataAttributesCreatedBy;
  updatedBy?: TestListResponseDataItemAttributesCreatedByDataAttributesUpdatedBy;
};
