/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TestResponseDataObject } from './testResponseDataObject';
import type { TestResponseMeta } from './testResponseMeta';

export interface TestResponse {
  data?: TestResponseDataObject;
  meta?: TestResponseMeta;
}
