/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderResponseDataObjectLocalizedAttributesCreatedByDataAttributes } from './uploadFolderResponseDataObjectLocalizedAttributesCreatedByDataAttributes';

export type UploadFolderResponseDataObjectLocalizedAttributesCreatedByData = {
  id?: number;
  attributes?: UploadFolderResponseDataObjectLocalizedAttributesCreatedByDataAttributes;
};
