/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesRelated } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesRelated';
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesFolder } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesFolder';
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedBy } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedBy';
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy';

export type UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesRelated;
  folder?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedBy;
  updatedBy?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy;
};
