/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFileListResponseDataItemAttributesFolderDataAttributesParent } from './uploadFileListResponseDataItemAttributesFolderDataAttributesParent';
import type { UploadFileListResponseDataItemAttributesFolderDataAttributesChildren } from './uploadFileListResponseDataItemAttributesFolderDataAttributesChildren';
import type { UploadFileListResponseDataItemAttributesFolderDataAttributesFiles } from './uploadFileListResponseDataItemAttributesFolderDataAttributesFiles';
import type { UploadFileListResponseDataItemAttributesFolderDataAttributesCreatedBy } from './uploadFileListResponseDataItemAttributesFolderDataAttributesCreatedBy';
import type { UploadFileListResponseDataItemAttributesFolderDataAttributesUpdatedBy } from './uploadFileListResponseDataItemAttributesFolderDataAttributesUpdatedBy';

export type UploadFileListResponseDataItemAttributesFolderDataAttributes = {
  name?: string;
  pathId?: number;
  parent?: UploadFileListResponseDataItemAttributesFolderDataAttributesParent;
  children?: UploadFileListResponseDataItemAttributesFolderDataAttributesChildren;
  files?: UploadFileListResponseDataItemAttributesFolderDataAttributesFiles;
  path?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFileListResponseDataItemAttributesFolderDataAttributesCreatedBy;
  updatedBy?: UploadFileListResponseDataItemAttributesFolderDataAttributesUpdatedBy;
};
