/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesRelated } from './uploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesRelated';
import type { UploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesFolder } from './uploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesFolder';
import type { UploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy } from './uploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy';
import type { UploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy } from './uploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy';

export type UploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: UploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesRelated;
  folder?: UploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy;
  updatedBy?: UploadFileResponseDataObjectAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy;
};
