/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesParent } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesParent';
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesChildren } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesChildren';
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFiles } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFiles';
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesCreatedBy } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesCreatedBy';
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesUpdatedBy } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesUpdatedBy';

export type UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributes = {
  name?: string;
  pathId?: number;
  parent?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesParent;
  children?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesChildren;
  files?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFiles;
  path?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesCreatedBy;
  updatedBy?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesUpdatedBy;
};
