/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderListResponseDataItem } from './uploadFolderListResponseDataItem';
import type { UploadFolderListResponseMeta } from './uploadFolderListResponseMeta';

export interface UploadFolderListResponse {
  data?: UploadFolderListResponseDataItem[];
  meta?: UploadFolderListResponseMeta;
}
