/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByDataAttributes } from './uploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByDataAttributes';

export type UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByData = {
  id?: number;
  attributes?: UploadFolderResponseDataObjectLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedByDataAttributesUpdatedByDataAttributes;
};
