/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFileResponseDataObjectLocalizedAttributesRelated } from './uploadFileResponseDataObjectLocalizedAttributesRelated';
import type { UploadFileResponseDataObjectLocalizedAttributesFolder } from './uploadFileResponseDataObjectLocalizedAttributesFolder';
import type { UploadFileResponseDataObjectLocalizedAttributesCreatedBy } from './uploadFileResponseDataObjectLocalizedAttributesCreatedBy';
import type { UploadFileResponseDataObjectLocalizedAttributesUpdatedBy } from './uploadFileResponseDataObjectLocalizedAttributesUpdatedBy';

export type UploadFileResponseDataObjectLocalizedAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: UploadFileResponseDataObjectLocalizedAttributesRelated;
  folder?: UploadFileResponseDataObjectLocalizedAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFileResponseDataObjectLocalizedAttributesCreatedBy;
  updatedBy?: UploadFileResponseDataObjectLocalizedAttributesUpdatedBy;
};
