/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderListResponseDataItemAttributesParentDataAttributesParent } from './uploadFolderListResponseDataItemAttributesParentDataAttributesParent';
import type { UploadFolderListResponseDataItemAttributesParentDataAttributesChildren } from './uploadFolderListResponseDataItemAttributesParentDataAttributesChildren';
import type { UploadFolderListResponseDataItemAttributesParentDataAttributesFiles } from './uploadFolderListResponseDataItemAttributesParentDataAttributesFiles';
import type { UploadFolderListResponseDataItemAttributesParentDataAttributesCreatedBy } from './uploadFolderListResponseDataItemAttributesParentDataAttributesCreatedBy';
import type { UploadFolderListResponseDataItemAttributesParentDataAttributesUpdatedBy } from './uploadFolderListResponseDataItemAttributesParentDataAttributesUpdatedBy';

export type UploadFolderListResponseDataItemAttributesParentDataAttributes = {
  name?: string;
  pathId?: number;
  parent?: UploadFolderListResponseDataItemAttributesParentDataAttributesParent;
  children?: UploadFolderListResponseDataItemAttributesParentDataAttributesChildren;
  files?: UploadFolderListResponseDataItemAttributesParentDataAttributesFiles;
  path?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFolderListResponseDataItemAttributesParentDataAttributesCreatedBy;
  updatedBy?: UploadFolderListResponseDataItemAttributesParentDataAttributesUpdatedBy;
};
