/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesRelated } from './uploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesRelated';
import type { UploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesFolder } from './uploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesFolder';
import type { UploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedBy } from './uploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedBy';
import type { UploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy } from './uploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy';

export type UploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: UploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesRelated;
  folder?: UploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesCreatedBy;
  updatedBy?: UploadFolderListResponseDataItemLocalizedAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy;
};
