/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderRequestDataParent } from './uploadFolderRequestDataParent';
import type { UploadFolderRequestDataChildrenItem } from './uploadFolderRequestDataChildrenItem';
import type { UploadFolderRequestDataFilesItem } from './uploadFolderRequestDataFilesItem';

export type UploadFolderRequestData = {
  name: string;
  pathId: number;
  parent?: UploadFolderRequestDataParent;
  children?: UploadFolderRequestDataChildrenItem[];
  files?: UploadFolderRequestDataFilesItem[];
  path: string;
};
