/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesRelated } from './uploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesRelated';
import type { UploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesFolder } from './uploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesFolder';
import type { UploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy } from './uploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy';
import type { UploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy } from './uploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy';

export type UploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: UploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesRelated;
  folder?: UploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesCreatedBy;
  updatedBy?: UploadFileResponseDataObjectLocalizedAttributesFolderDataAttributesFilesDataItemAttributesUpdatedBy;
};
