/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderListResponseDataItemAttributesParent } from './uploadFolderListResponseDataItemAttributesParent';
import type { UploadFolderListResponseDataItemAttributesChildren } from './uploadFolderListResponseDataItemAttributesChildren';
import type { UploadFolderListResponseDataItemAttributesFiles } from './uploadFolderListResponseDataItemAttributesFiles';
import type { UploadFolderListResponseDataItemAttributesCreatedBy } from './uploadFolderListResponseDataItemAttributesCreatedBy';
import type { UploadFolderListResponseDataItemAttributesUpdatedBy } from './uploadFolderListResponseDataItemAttributesUpdatedBy';

export type UploadFolderListResponseDataItemAttributes = {
  name?: string;
  pathId?: number;
  parent?: UploadFolderListResponseDataItemAttributesParent;
  children?: UploadFolderListResponseDataItemAttributesChildren;
  files?: UploadFolderListResponseDataItemAttributesFiles;
  path?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFolderListResponseDataItemAttributesCreatedBy;
  updatedBy?: UploadFolderListResponseDataItemAttributesUpdatedBy;
};
