/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesRelated } from './uploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesRelated';
import type { UploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesFolder } from './uploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesFolder';
import type { UploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesCreatedBy } from './uploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesCreatedBy';
import type { UploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy } from './uploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy';

export type UploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: UploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesRelated;
  folder?: UploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesCreatedBy;
  updatedBy?: UploadFolderResponseDataObjectAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy;
};
