/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesRelated } from './uploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesRelated';
import type { UploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesFolder } from './uploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesFolder';
import type { UploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesCreatedBy } from './uploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesCreatedBy';
import type { UploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy } from './uploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy';

export type UploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: UploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesRelated;
  folder?: UploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesCreatedBy;
  updatedBy?: UploadFolderListResponseDataItemAttributesParentDataAttributesFilesDataItemAttributesUpdatedBy;
};
