/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFileListResponseDataItemAttributesRelated } from './uploadFileListResponseDataItemAttributesRelated';
import type { UploadFileListResponseDataItemAttributesFolder } from './uploadFileListResponseDataItemAttributesFolder';
import type { UploadFileListResponseDataItemAttributesCreatedBy } from './uploadFileListResponseDataItemAttributesCreatedBy';
import type { UploadFileListResponseDataItemAttributesUpdatedBy } from './uploadFileListResponseDataItemAttributesUpdatedBy';

export type UploadFileListResponseDataItemAttributes = {
  name?: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: UploadFileListResponseDataItemAttributesRelated;
  folder?: UploadFileListResponseDataItemAttributesFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UploadFileListResponseDataItemAttributesCreatedBy;
  updatedBy?: UploadFileListResponseDataItemAttributesUpdatedBy;
};
