/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFolderListResponseDataItemLocalizedAttributesFilesDataItem } from './uploadFolderListResponseDataItemLocalizedAttributesFilesDataItem';

export type UploadFolderListResponseDataItemLocalizedAttributesFiles = {
  data?: UploadFolderListResponseDataItemLocalizedAttributesFilesDataItem[];
};
