/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesCreatedByDataAttributes } from './usersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesCreatedByDataAttributes';

export type UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesCreatedByData = {
  id?: number;
  attributes?: UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesCreatedByDataAttributes;
};
