/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissions } from './usersPermissionsRoleResponseDataObjectLocalizedAttributesPermissions';
import type { UsersPermissionsRoleResponseDataObjectLocalizedAttributesUsers } from './usersPermissionsRoleResponseDataObjectLocalizedAttributesUsers';
import type { UsersPermissionsRoleResponseDataObjectLocalizedAttributesCreatedBy } from './usersPermissionsRoleResponseDataObjectLocalizedAttributesCreatedBy';
import type { UsersPermissionsRoleResponseDataObjectLocalizedAttributesUpdatedBy } from './usersPermissionsRoleResponseDataObjectLocalizedAttributesUpdatedBy';

export type UsersPermissionsRoleResponseDataObjectLocalizedAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissions;
  users?: UsersPermissionsRoleResponseDataObjectLocalizedAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsRoleResponseDataObjectLocalizedAttributesCreatedBy;
  updatedBy?: UsersPermissionsRoleResponseDataObjectLocalizedAttributesUpdatedBy;
};
