/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUserListResponseDataItemAttributesRole } from './usersPermissionsUserListResponseDataItemAttributesRole';
import type { UsersPermissionsUserListResponseDataItemAttributesCreatedBy } from './usersPermissionsUserListResponseDataItemAttributesCreatedBy';
import type { UsersPermissionsUserListResponseDataItemAttributesUpdatedBy } from './usersPermissionsUserListResponseDataItemAttributesUpdatedBy';

export type UsersPermissionsUserListResponseDataItemAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: UsersPermissionsUserListResponseDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsUserListResponseDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsUserListResponseDataItemAttributesUpdatedBy;
};
