/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributesRole } from './usersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributesRole';
import type { UsersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy } from './usersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy';
import type { UsersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy } from './usersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy';

export type UsersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributes = {
  action?: string;
  role?: UsersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsUserResponseDataObjectAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy;
};
