/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesRole } from './usersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesRole';
import type { UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesCreatedBy } from './usersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesCreatedBy';
import type { UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesUpdatedBy } from './usersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesUpdatedBy';

export type UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributes = {
  action?: string;
  role?: UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesUpdatedBy;
};
