/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesRole } from './usersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesRole';
import type { UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedBy } from './usersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedBy';
import type { UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesUpdatedBy } from './usersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesUpdatedBy';

export type UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesUpdatedBy;
};
