/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesRoleDataAttributesPermissionsDataItemAttributes } from './usersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesRoleDataAttributesPermissionsDataItemAttributes';

export type UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesRoleDataAttributesPermissionsDataItem = {
  id?: number;
  attributes?: UsersPermissionsRoleResponseDataObjectLocalizedAttributesPermissionsDataItemAttributesRoleDataAttributesPermissionsDataItemAttributes;
};
