/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesRole } from './usersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesRole';
import type { UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesCreatedBy } from './usersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesCreatedBy';
import type { UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesUpdatedBy } from './usersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesUpdatedBy';

export type UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributes = {
  action?: string;
  role?: UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesUpdatedBy;
};
