/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions } from './usersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions';
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers } from './usersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers';
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesCreatedBy } from './usersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesCreatedBy';
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUpdatedBy } from './usersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUpdatedBy';

export type UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions;
  users?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesCreatedBy;
  updatedBy?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUpdatedBy;
};
