/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesRole } from './usersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesRole';
import type { UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesCreatedBy } from './usersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesCreatedBy';
import type { UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesUpdatedBy } from './usersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesUpdatedBy';

export type UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesUpdatedBy;
};
