/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleResponseDataObject } from './usersPermissionsRoleResponseDataObject';
import type { UsersPermissionsRoleResponseMeta } from './usersPermissionsRoleResponseMeta';

export interface UsersPermissionsRoleResponse {
  data?: UsersPermissionsRoleResponseDataObject;
  meta?: UsersPermissionsRoleResponseMeta;
}
