/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissions } from './usersPermissionsRoleListResponseDataItemLocalizedAttributesPermissions';
import type { UsersPermissionsRoleListResponseDataItemLocalizedAttributesUsers } from './usersPermissionsRoleListResponseDataItemLocalizedAttributesUsers';
import type { UsersPermissionsRoleListResponseDataItemLocalizedAttributesCreatedBy } from './usersPermissionsRoleListResponseDataItemLocalizedAttributesCreatedBy';
import type { UsersPermissionsRoleListResponseDataItemLocalizedAttributesUpdatedBy } from './usersPermissionsRoleListResponseDataItemLocalizedAttributesUpdatedBy';

export type UsersPermissionsRoleListResponseDataItemLocalizedAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissions;
  users?: UsersPermissionsRoleListResponseDataItemLocalizedAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsRoleListResponseDataItemLocalizedAttributesCreatedBy;
  updatedBy?: UsersPermissionsRoleListResponseDataItemLocalizedAttributesUpdatedBy;
};
