/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionResponseDataObjectLocalizedAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedByDataAttributes } from './usersPermissionsPermissionResponseDataObjectLocalizedAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedByDataAttributes';

export type UsersPermissionsPermissionResponseDataObjectLocalizedAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedByData = {
  id?: number;
  attributes?: UsersPermissionsPermissionResponseDataObjectLocalizedAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedByDataAttributes;
};
