/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleResponseDataObjectAttributesPermissions } from './usersPermissionsRoleResponseDataObjectAttributesPermissions';
import type { UsersPermissionsRoleResponseDataObjectAttributesUsers } from './usersPermissionsRoleResponseDataObjectAttributesUsers';
import type { UsersPermissionsRoleResponseDataObjectAttributesCreatedBy } from './usersPermissionsRoleResponseDataObjectAttributesCreatedBy';
import type { UsersPermissionsRoleResponseDataObjectAttributesUpdatedBy } from './usersPermissionsRoleResponseDataObjectAttributesUpdatedBy';

export type UsersPermissionsRoleResponseDataObjectAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: UsersPermissionsRoleResponseDataObjectAttributesPermissions;
  users?: UsersPermissionsRoleResponseDataObjectAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsRoleResponseDataObjectAttributesCreatedBy;
  updatedBy?: UsersPermissionsRoleResponseDataObjectAttributesUpdatedBy;
};
