/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionResponseDataObjectAttributesUpdatedByDataAttributes } from './usersPermissionsPermissionResponseDataObjectAttributesUpdatedByDataAttributes';

export type UsersPermissionsPermissionResponseDataObjectAttributesUpdatedByData = {
  id?: number;
  attributes?: UsersPermissionsPermissionResponseDataObjectAttributesUpdatedByDataAttributes;
};
