/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedByDataAttributes } from './usersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedByDataAttributes';

export type UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedByData = {
  id?: number;
  attributes?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedByDataAttributes;
};
