/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRole } from './usersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRole';
import type { UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesCreatedBy } from './usersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesCreatedBy';
import type { UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesUpdatedBy } from './usersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesUpdatedBy';

export type UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributes = {
  action?: string;
  role?: UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsRoleResponseDataObjectAttributesPermissionsDataItemAttributesUpdatedBy;
};
