/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleListResponseDataItemAttributesPermissions } from './usersPermissionsRoleListResponseDataItemAttributesPermissions';
import type { UsersPermissionsRoleListResponseDataItemAttributesUsers } from './usersPermissionsRoleListResponseDataItemAttributesUsers';
import type { UsersPermissionsRoleListResponseDataItemAttributesCreatedBy } from './usersPermissionsRoleListResponseDataItemAttributesCreatedBy';
import type { UsersPermissionsRoleListResponseDataItemAttributesUpdatedBy } from './usersPermissionsRoleListResponseDataItemAttributesUpdatedBy';

export type UsersPermissionsRoleListResponseDataItemAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: UsersPermissionsRoleListResponseDataItemAttributesPermissions;
  users?: UsersPermissionsRoleListResponseDataItemAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsRoleListResponseDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsRoleListResponseDataItemAttributesUpdatedBy;
};
