/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUserListResponseDataItemLocalizedAttributesRole } from './usersPermissionsUserListResponseDataItemLocalizedAttributesRole';
import type { UsersPermissionsUserListResponseDataItemLocalizedAttributesCreatedBy } from './usersPermissionsUserListResponseDataItemLocalizedAttributesCreatedBy';
import type { UsersPermissionsUserListResponseDataItemLocalizedAttributesUpdatedBy } from './usersPermissionsUserListResponseDataItemLocalizedAttributesUpdatedBy';

export type UsersPermissionsUserListResponseDataItemLocalizedAttributes = {
  username?: string;
  email?: string;
  provider?: string;
  resetPasswordToken?: string;
  confirmationToken?: string;
  confirmed?: boolean;
  blocked?: boolean;
  role?: UsersPermissionsUserListResponseDataItemLocalizedAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsUserListResponseDataItemLocalizedAttributesCreatedBy;
  updatedBy?: UsersPermissionsUserListResponseDataItemLocalizedAttributesUpdatedBy;
};
