/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesUpdatedByData } from './usersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesUpdatedByData';

export type UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesUpdatedBy = {
  data?: UsersPermissionsUserResponseDataObjectLocalizedAttributesRoleDataAttributesUsersDataItemAttributesUpdatedByData;
};
