/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionListResponseDataItemAttributesRole } from './usersPermissionsPermissionListResponseDataItemAttributesRole';
import type { UsersPermissionsPermissionListResponseDataItemAttributesCreatedBy } from './usersPermissionsPermissionListResponseDataItemAttributesCreatedBy';
import type { UsersPermissionsPermissionListResponseDataItemAttributesUpdatedBy } from './usersPermissionsPermissionListResponseDataItemAttributesUpdatedBy';

export type UsersPermissionsPermissionListResponseDataItemAttributes = {
  action?: string;
  role?: UsersPermissionsPermissionListResponseDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsPermissionListResponseDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsPermissionListResponseDataItemAttributesUpdatedBy;
};
