/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUserListResponseDataItemLocalizedAttributesUpdatedByDataAttributes } from './usersPermissionsUserListResponseDataItemLocalizedAttributesUpdatedByDataAttributes';

export type UsersPermissionsUserListResponseDataItemLocalizedAttributesUpdatedByData = {
  id?: number;
  attributes?: UsersPermissionsUserListResponseDataItemLocalizedAttributesUpdatedByDataAttributes;
};
