/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributesRole } from './usersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributesRole';
import type { UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributesCreatedBy } from './usersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributesCreatedBy';
import type { UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributesUpdatedBy } from './usersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributesUpdatedBy';

export type UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributes = {
  action?: string;
  role?: UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataItemAttributesUpdatedBy;
};
