/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionListResponseDataItemLocalizedAttributesRole } from './usersPermissionsPermissionListResponseDataItemLocalizedAttributesRole';
import type { UsersPermissionsPermissionListResponseDataItemLocalizedAttributesCreatedBy } from './usersPermissionsPermissionListResponseDataItemLocalizedAttributesCreatedBy';
import type { UsersPermissionsPermissionListResponseDataItemLocalizedAttributesUpdatedBy } from './usersPermissionsPermissionListResponseDataItemLocalizedAttributesUpdatedBy';

export type UsersPermissionsPermissionListResponseDataItemLocalizedAttributes = {
  action?: string;
  role?: UsersPermissionsPermissionListResponseDataItemLocalizedAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsPermissionListResponseDataItemLocalizedAttributesCreatedBy;
  updatedBy?: UsersPermissionsPermissionListResponseDataItemLocalizedAttributesUpdatedBy;
};
