/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionListResponseDataItem } from './usersPermissionsPermissionListResponseDataItem';
import type { UsersPermissionsPermissionListResponseMeta } from './usersPermissionsPermissionListResponseMeta';

export interface UsersPermissionsPermissionListResponse {
  data?: UsersPermissionsPermissionListResponseDataItem[];
  meta?: UsersPermissionsPermissionListResponseMeta;
}
