/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesPermissions } from './usersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesPermissions';
import type { UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesUsers } from './usersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesUsers';
import type { UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesCreatedBy } from './usersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesCreatedBy';
import type { UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesUpdatedBy } from './usersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesUpdatedBy';

export type UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributes = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesPermissions;
  users?: UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesUsers;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesCreatedBy;
  updatedBy?: UsersPermissionsPermissionResponseDataObjectAttributesRoleDataAttributesUpdatedBy;
};
