/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedByDataAttributes } from './usersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedByDataAttributes';

export type UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedByData = {
  id?: number;
  attributes?: UsersPermissionsRoleListResponseDataItemLocalizedAttributesPermissionsDataItemAttributesRoleDataAttributesUsersDataItemAttributesCreatedByDataAttributes;
};
