/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributesRole } from './usersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributesRole';
import type { UsersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy } from './usersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy';
import type { UsersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy } from './usersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy';

export type UsersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributes = {
  action?: string;
  role?: UsersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: UsersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: UsersPermissionsUserListResponseDataItemAttributesRoleDataAttributesPermissionsDataItemAttributesUpdatedBy;
};
